#!/usr/bin/env python3
"""Globomantics Data Processing API — single process for all three lab objectives.

Students do not edit this file. Each objective lives in its own module:

    obj1_memory.py    POST /api/v1/pack
    obj2_ingest.py    POST /api/v1/ingest
    obj3_validate.py  POST /api/v1/jobs

The matching *_secure.py files are answer keys for VS Code Compare Selected.
They are not imported here.

    ./run.sh
"""
from fastapi import FastAPI

from obj1_memory import router as memory_router
from obj2_ingest import router as ingest_router
from obj3_validate import router as validate_router

app = FastAPI(
    title="Globomantics Data Processing API",
    description="Warehouse telemetry packer, partner YAML ingest, and JSON job intake.",
    version="1.0.0",
)
app.include_router(memory_router)
app.include_router(ingest_router)
app.include_router(validate_router)


@app.get("/health")
def health():
    return {
        "service": "globomantics-data-processing",
        "status": "ok",
        "version": "1.0.0",
    }
